### ISSUE TITLE
Updating from 2022-12 CPP on Linux x86-64 to 2023-03 M2 fails on restart

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-justj/justj#2]
Doing the pre-publish tests in https://hackmd.io/@jonahgraham/eclipse-epp-release-process I hit the below error that seems to happen because JustJ updated. 

The installation completed fine, but instead of sucessfully restarting I got this pop-up error.

Closing the error and manually starting Eclipse worked fine.

![image](https://user-images.githubusercontent.com/679236/216433531-52cda79e-7c25-49e0-948f-7a9c05c01996.png)

<details><summary>contents of screenshot</summary>

```
/tmp/a/eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.6.v20230125-1136/jre/bin
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
-Dosgi.requiredJavaVersion=17
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Dsun.java.command=Eclipse
-Xms256m
-Xmx2048m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-jar
/tmp/a/eclipse//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
-os
linux
-ws
gtk
-arch
x86_64
-showsplash
/tmp/a/eclipse//plugins/org.eclipse.epp.package.common_4.26.0.20221201-1200/splash.bmp
-launcher
/tmp/a/eclipse/eclipse
-name
Eclipse
--launcher.library
/tmp/a/eclipse//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024/eclipse_11801.so
-startup
/tmp/a/eclipse//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.appendVmargs
-exitdata
10027
-product
org.eclipse.epp.package.cpp.product
-data
file:/tmp/a/data/
-consoleLog
-vm
/tmp/a/eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.6.v20230125-1136/jre/bin
-vmargs
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
-Dosgi.requiredJavaVersion=17
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Dsun.java.command=Eclipse
-Xms256m
-Xmx2048m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-jar
/tmp/a/eclipse//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
```

</details>

**Comment by jonahgraham** [comment]
I'm doing some other tests to try to verify it really was JustJ updating that did this.

**Comment by jonahgraham** [comment]
It does seem to be JustJ related. Starting with `eclipse-cpp-2022-12-R-linux-gtk-x86_64.tar.gz` and then installing justj 17.0.6 complete leads to the same error.

![image](https://user-images.githubusercontent.com/679236/216439390-1dd33341-fbc9-43ec-ad5b-0f399e2c4565.png)

**Comment by merks** [comment]
This works for me on Windows.

I know that in the past, special steps were taken in p2 to make this work:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=551378

Mostly adding this:

https://github.com/eclipse-equinox/p2/blob/c738408a533dd264182ecfffcd8c2dfdad62d337/bundles/org.eclipse.equinox.p2.touchpoint.eclipse/src/org/eclipse/equinox/internal/p2/touchpoint/eclipse/actions/SetJvmAction.java#L72-L103

So it's unlikely this is a JustJ issue but rather a p2 issue.  Is there a log file in the configuration folder that might provide a clue what's going wrong?  I assume it didn't get far enough to log into the workspace's log...

**Comment by jonahgraham** [comment]
I'm glad it works on Windows, that covers a large portion of the users.

The reason it works on Windows is that when the JVM changes eclipse restarts the eclipse.exe process, but on Linux it launches a new child java.

_This is because on Windows by default it uses JNI so the eclipse.exe process is the java process._

The code in Equinox for SetJvmAction expects the the executable name for java to be provided as that argument is what it uses to launch the restarted eclipse. Since the p2.inf does this:

```
  org.eclipse.equinox.p2.touchpoint.eclipse.setJvm(jvm:${artifact.location}/jre/bin);\
```

The process that is attempted to launch is the folder, which fails. This is what the first line of the OP shows:

```
/tmp/a/eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.6.v20230125-1136/jre/bin
```

Therefore, I believe the correct fix is, on Linux, to include `java` in the `setJvm` action point.

PR provided in #4. However I have not built justj to test it, I am hoping the PR gets built and gives me something testable?

**Comment by jonahgraham** [comment]
> PR provided in https://github.com/eclipse-justj/justj/pull/4. However I have not built justj to test it, I am hoping the PR gets built and gives me something testable?

Thanks Ed, with the https://download.eclipse.org/justj/jres/17/updates/nightly/N202302040753/ build restart now works correctly on Linux.

**Comment by merks** [comment]
Awesome.  🚀  I will respin release builds over the weekend.

**Comment by merks** [comment]
FYI, this:

https://download.eclipse.org/justj/jres/17/updates/release/latest

points at this with the changes:

https://download.eclipse.org/justj/jres/17/updates/release/17.0.6.v20230204-1729
