### ISSUE TITLE
Provide JREs for Windows aarch64

### ISSUE THREAD

**Issue by HannesWell** [eclipse-justj/justj#26]
At the moment for Windows JustJ provides only artifacts for the `x86_64` architecture.
It would be great if JustJ could also provide JREs for Windows on ARM64/aarch64, similar to 
https://github.com/eclipse-justj/justj/issues/12.

Because there is currently some work happening to make Eclipse also available for Windows on Arm, especially https://github.com/eclipse-platform/eclipse.platform.swt/pull/1045, it would be very convenient if JustJ would provide such artifacts. And of course users of Eclipse would also benefit from it.

**Comment by HannesWell** [comment]
Looking at the Adoptium website I can't see a JDK provided for Windows on ARM, which of course makes it difficult for JustJ to adopt them: https://github.com/adoptium/adoptium-support/issues/616

Searching their issues leads to https://github.com/adoptium/adoptium-support/issues/616 and when following the references to that issue I see that it seems to be a known problem.

**Comment by merks** [comment]
This was contributed 

https://github.com/eclipse-justj/justj/pull/1

but the adoptium progress hasn’t happened.
