### ISSUE TITLE
Time for updated JustJ runtime version after Temurin release

### ISSUE THREAD

**Issue by minduch** [eclipse-justj/justj#27]
When will JustJ v 22.02 and 21.0.4 LTS be ready?
How long does it take to produce the JustJ runtimes in all the forms, once Eclipse Temurin versions are ready?

(I'ts not only Eclipse IDE that depends on having these newer Java versions)...

**Comment by minduch** [comment]
And let's not forget the need to a Temurin for Windows on ARM64 accompanied by an Eclipse + JustJ version of that platform...

**Comment by merks** [comment]
It didn’t notice new versions were ready. 

It takes just a few hours to build them.  I’ll try to get it done Friday.   

Thanks for the heads up!

**Comment by merks** [comment]
Well, it's a few hours, times 4 versions, + broken tools that need fixing first!  😱 

There are now new JustJ releases for Java 11, 17, 21, and 22 available.  🎉
