### ISSUE TITLE
Add support for Class Data Sharing (CDS)

### ISSUE THREAD

**Issue by tivervac** [eclipse-justj/justj#28]
[CDS](https://docs.oracle.com/javase/8/docs/technotes/guides/vm/class-data-sharing.html) can improve the startup speed of the JVM at the cost of a slightly larger binary size.

To enable it, [this](https://docs.oracle.com/en/java/javase/21/docs/specs/man/jlink.html#plugin-generate-cds-archive) option needs to be enabled in JLink. This option has been available since Java 18.

**Comment by merks** [comment]
These JREs packages

https://download.eclipse.org/justj/jres/21/downloads/latest/

and these JRE updates

https://download.eclipse.org/justj/jres/21/updates/nightly/latest

are generated using jlink with --generate-cds-archive

@tivervac 

Will you do some kind of testing/verification that this is working well/correctly?

I don't think it's a good idea to change the JRE used by EPP/SimRel this close to the release during RC1...

@jukzi

As our resident performance expert, I wonder if this yields any measurable performance improvements?

**Comment by jukzi** [comment]
Repeatedly measuring hello world example on windows:
```
	public static void main(String[] args) {
		System.out.println("hi"); 
	}
```
like
`Measure-Command {&"C:\java\org.eclipse.justj.openjdk.hotspot.jre.full-21.0.4-win32-x86_64 2024-08-26\bin\java" -classpath "C:\Users\jkubitz\platform-2024-08-26\git\eclipse.platform\resources\bundles\org.eclipse.core.resources\bin" "org.eclipse.core.resources.Main" | Out-Default}`

results at best in
2024-08-26: 153ms
2024-08-02: 172ms

i.e. the new version starts up 20ms faster on my computer.

https://ftp.linux.org.tr/eclipse//justj/jres/21/downloads/20240826_1527/org.eclipse.justj.openjdk.hotspot.jre.full-21.0.4-win32-x86_64.tar.gz
https://mirror.leitecastro.com/eclipse/justj/jres/21/downloads/20240802_1234/org.eclipse.justj.openjdk.hotspot.jre.full-21.0.4-win32-x86_64.tar.gz

**Comment by merks** [comment]
Thanks!  That's not an appreciable difference.  I'm not sure what the default for `-Xshare:*`: but probably `-Xshare:off` but maybe auto?

https://docs.oracle.com/javase/8/docs/technotes/guides/vm/class-data-sharing.html

The difference might not be noticeable for such a tine application I suppose...

@tivervac 

What kinds of results are you expecting?

**Comment by jukzi** [comment]
The download size differs by ~7MB (120MB vs 127MB).  Assuming a download transfer rate of 100MBit the download takes ~0.5 sec longer which would be compensated by 28*20ms i.e. after 28 java starts which might scratch a realistic number of starts for an ordinary user.
If my benchmark is ill please suggest any other method to measure. I was astonished that even with this very simple example i could see a measurable difference.

**Comment by merks** [comment]
Very good!  That the default is auto is also very convenient, then we don't need to provide options for this to end up being used.  👍

**Comment by tivervac** [comment]
I didn't expect the changes to be added as quickly. Right now is a busy time for me, but I'll look into it ASAP!
