### ISSUE TITLE
JustJ does not update to 17.0.6

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-justj/justj#3]
With the recent release of JustJ for Java 17.0.6 I expected that the 2022-12 installs of EPP would update, unfortunately they do not, instead reporting as all up to date.

An update from 2022-12 -> 2023-03 M2 does update JustJ.

![image](https://user-images.githubusercontent.com/679236/216436917-e313b37f-002a-40cd-a729-bcfe88ba0017.png)

This is how it shows up as installed:

![image](https://user-images.githubusercontent.com/679236/216436990-caf9034d-9fe3-4331-9ce2-2e622c79de92.png)

The latest update site appears in the IDE by default and it shows 17.0.6, but none of the packages are listed as upgrades

![image](https://user-images.githubusercontent.com/679236/216437201-b36ef590-400d-41e0-b14b-3a729e216f0b.png)

And the "for IDE packages" shows all items installed

![image](https://user-images.githubusercontent.com/679236/216437267-24895c73-a07b-449e-b26d-befabd0bf832.png)

**Comment by jonahgraham** [comment]
Weirdly updating 2022-12 to SimRel 2023-03 M1 (\*), the version that was released before JustJ 17.0.6 IIUC, updates JustJ even though it doesn't show up as an update candidate in the check for updates wizard.

\* Done by adding `https://download.eclipse.org/releases/2023-03` to available software sites and doing a check for updates.

**Comment by merks** [comment]
Yes, minimally the qualifier needs to change each time there is a new Java 17 version available.  I've done that now and test that it works:

![image](https://user-images.githubusercontent.com/208716/216555461-ca239983-afed-409c-8108-889ee7262232.png)
