### ISSUE TITLE
java.xml.crypto is needed by org.apache.poi.ooxml

### ISSUE THREAD

**Issue by daus-salar** [eclipse-justj/justj#31]
The module java.xml.crypto  is needed by org.apache.poi.ooxml since Apache POI 5.3.0 is part of the Orbit Simultaneous Release we think it is a bug that org.apache.poi.ooxml is not working with "JustJ Adoptium OpenJDK Hotspot JRE Minimal".

**Comment by merks** [comment]
It's part of Orbit but it's not part of SimRel.   

![image](https://github.com/user-attachments/assets/f330a011-6adb-4f3d-9a9c-e3fd18950875)

So it's certainly not a bug.  I suspect that if I simply keep adding things to minimal, which is primarily used by the Eclipse Installer, it will end up being close to full/complete in the long term.

I'm not sure how big that module.  It's probably just a small thing to add.  I'll give it some though for the next JRE releases...

**Comment by daus-salar** [comment]
Oh, I see. Thank you for considering to add it.

We have some pain with org.apache.poi and updating it in our  RCP Application with minimal JustJ JRE.

**Comment by merks** [comment]
It's available in this latest nightly build:

https://download.eclipse.org/justj/jres/21/updates/nightly/latest

The next releases (maybe around December) will include it as well.  It appears to at about 1MB to the jar size.  Please test to confirm that it addresses the issue before the next release cycle.
